// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/i18n/build_i18n.dart

// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars

import 'package:flutter/widgets.dart';

/// Supported locale codes
const List<String> kSupportedLocales = [
  'en',
  'es',
];

/// Base class for all translations
abstract class AppStrings {
  String get a11yBackButton;
  String get a11yCloseButton;
  String get a11yMenuButton;
  String get a11yProLockedFeature;
  String get a11yQualitySlider;
  String get a11ySaveButton;
  String get a11ySessionTimer;
  String get actionClose;
  String get actionCopy;
  String get actionDelete;
  String get actionDone;
  String get actionEdit;
  String get actionPause;
  String get actionRefresh;
  String get actionResume;
  String get actionShare;
  String get actionStart;
  String get actionStop;
  String get analyticsAverageQuality;
  String get analyticsBestStreak;
  String get analyticsKeywordAnalysis;
  String get analyticsMoodCorrelation;
  String get analyticsTagPerformance;
  String get analyticsTitle;
  String get analyticsTotalSessions;
  String get analyticsTotalTime;
  String get analyticsUnlimitedHistory;
  String get appName;
  String get appSubtitle;
  String get billingCancelAnytime;
  String get billingCancelled;
  String get billingError;
  String get billingManage;
  String get billingProcessing;
  String get billingRestore;
  String get billingSuccess;
  String get coachFirstTip;
  String get coachGoalReminder;
  String get coachImprovementTip;
  String get coachStreakMotivation;
  String get coachWelcome;
  String get diagnosticsDisabled;
  String get diagnosticsEnabled;
  String get diagnosticsPanel;
  String get dialogCancel;
  String get dialogConfirm;
  String get dialogDelete;
  String get dialogDeleteSession;
  String get dialogDiscardChanges;
  String get dialogExportDataMessage;
  String get dialogExportDataTitle;
  String get dialogResetData;
  String get dialogSave;
  String get errorBillingUnavailable;
  String get errorDataExportFailed;
  String get errorGeneral;
  String get errorInvalidInput;
  String get errorNetwork;
  String get errorSessionSaveFailed;
  String get goalCompleted;
  String get goalCurrentProgress;
  String get goalSessionsPerWeek;
  String get goalWeekly;
  String get moodCalm;
  String get moodCheckin;
  String get moodEnergetic;
  String get moodFocused;
  String get moodNeutral;
  String get moodStressed;
  String get moodTired;
  String get navAnalytics;
  String get navGoals;
  String get navSessions;
  String get navSettings;
  String get onboardingGetStarted;
  String get onboardingNext;
  String get onboardingSkip;
  String get onboardingStep1Desc;
  String get onboardingStep1Title;
  String get onboardingStep2Desc;
  String get onboardingStep2Title;
  String get onboardingStep3Desc;
  String get onboardingStep3Title;
  String get proFeatureDataExport;
  String get proFeatureKeywordExtraction;
  String get proFeatureMoodInsights;
  String get proFeatureTagAnalytics;
  String get proFeatureUnlimitedHistory;
  String get proFreeTrial;
  String get proLocked;
  String get proMonthly;
  String get proSavePercent;
  String get proSubtitle;
  String get proTitle;
  String get proUnlockHint;
  String get proUpgrade;
  String get proYearly;
  String get purchaseCheckStatus;
  String get purchasePending;
  String get purchaseTimeoutMessage;
  String get purchaseWaiting;
  String get qualityExcellent;
  String get qualityFair;
  String get qualityGood;
  String get qualityPoor;
  String get qualityVeryGood;
  String get restoreTimeout;
  String get sessionDiscard;
  String get sessionDuration;
  String get sessionNotesPlaceholder;
  String get sessionQualityRating;
  String get sessionSave;
  String get sessionTagsPlaceholder;
  String get sessionTitle;
  String get settingsAbout;
  String get settingsDataExport;
  String get settingsEnglish;
  String get settingsHighContrast;
  String get settingsLanguage;
  String get settingsNotifications;
  String get settingsPrivacy;
  String get settingsReminderTime;
  String get settingsSpanish;
  String get settingsSupport;
  String get settingsSystemLanguage;
  String get settingsTitle;
  String get settingsVersion;
  String get splashInitializing;
  String get splashLoading;
  String get startBeginJourney;
  String get startContinueTraining;
  String get startFirstSession;
  String get startWelcome;
  String get streakDaily;
  String get streakDays;
  String get streakWeekly;
  String get streakWeeks;
  String get supportBundleCreated;
  String get supportContact;
  String get supportCreateBundle;
  String get supportExportLogs;
  String get supportLogs;
  String get supportTitle;
  String get timeHoursShort;
  String get timeLastWeek;
  String get timeMinutesShort;
  String get timeSecondsShort;
  String get timeThisWeek;
  String get timeToday;
  String get timeYesterday;
  String get toastGoalUpdated;
  String get toastProUnlocked;
  String get toastPurchaseRestored;
  String get toastSessionSaved;
  String get toastSettingsSaved;

  /// Replace parameters in a string (e.g., {name} -> John)
  String replace(String template, Map<String, dynamic> params) {
    var result = template;
    for (final entry in params.entries) {
      result = result.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return result;
  }
}

/// Strings for en locale
class AppStringsEN extends AppStrings {
  @override
  String get a11yBackButton => 'Back button';
  @override
  String get a11yCloseButton => 'Close button';
  @override
  String get a11yMenuButton => 'Menu button';
  @override
  String get a11yProLockedFeature => 'Pro feature locked';
  @override
  String get a11yQualitySlider => 'Quality rating slider';
  @override
  String get a11ySaveButton => 'Save button';
  @override
  String get a11ySessionTimer => 'Session timer';
  @override
  String get actionClose => 'Close';
  @override
  String get actionCopy => 'Copy';
  @override
  String get actionDelete => 'Delete';
  @override
  String get actionDone => 'Done';
  @override
  String get actionEdit => 'Edit';
  @override
  String get actionPause => 'Pause';
  @override
  String get actionRefresh => 'Refresh';
  @override
  String get actionResume => 'Resume';
  @override
  String get actionShare => 'Share';
  @override
  String get actionStart => 'Start';
  @override
  String get actionStop => 'Stop';
  @override
  String get analyticsAverageQuality => 'Average Quality';
  @override
  String get analyticsBestStreak => 'Best Streak';
  @override
  String get analyticsKeywordAnalysis => 'Keyword Analysis';
  @override
  String get analyticsMoodCorrelation => 'Mood Correlation';
  @override
  String get analyticsTagPerformance => 'Tag Performance';
  @override
  String get analyticsTitle => 'Analytics';
  @override
  String get analyticsTotalSessions => 'Total Sessions';
  @override
  String get analyticsTotalTime => 'Total Time';
  @override
  String get analyticsUnlimitedHistory => 'Unlimited History';
  @override
  String get appName => 'MindTrainer';
  @override
  String get appSubtitle => 'Focus Training for Mental Clarity';
  @override
  String get billingCancelAnytime => 'Cancel anytime';
  @override
  String get billingCancelled => 'Purchase cancelled';
  @override
  String get billingError => 'Purchase failed';
  @override
  String get billingManage => 'Manage Subscription';
  @override
  String get billingProcessing => 'Processing purchase...';
  @override
  String get billingRestore => 'Restore Purchases';
  @override
  String get billingSuccess => 'Purchase successful!';
  @override
  String get coachFirstTip => 'Start with short 10-minute sessions';
  @override
  String get coachGoalReminder => 'Don\t forget your weekly goal';
  @override
  String get coachImprovementTip => 'Try focusing on your breathing';
  @override
  String get coachStreakMotivation => 'Great streak! Keep it going';
  @override
  String get coachWelcome => 'Hello! I\m your focus coach';
  @override
  String get diagnosticsDisabled => 'Diagnostics disabled';
  @override
  String get diagnosticsEnabled => 'Diagnostics enabled';
  @override
  String get diagnosticsPanel => 'Diagnostics Panel';
  @override
  String get dialogCancel => 'Cancel';
  @override
  String get dialogConfirm => 'Confirm';
  @override
  String get dialogDelete => 'Delete';
  @override
  String get dialogDeleteSession => 'Delete this session?';
  @override
  String get dialogDiscardChanges => 'Discard changes?';
  @override
  String get dialogExportDataMessage => 'Export your session data as CSV?';
  @override
  String get dialogExportDataTitle => 'Export Data';
  @override
  String get dialogResetData => 'Reset all data?';
  @override
  String get dialogSave => 'Save';
  @override
  String get errorBillingUnavailable => 'Billing service unavailable';
  @override
  String get errorDataExportFailed => 'Failed to export data';
  @override
  String get errorGeneral => 'Something went wrong';
  @override
  String get errorInvalidInput => 'Invalid input';
  @override
  String get errorNetwork => 'Network connection required';
  @override
  String get errorSessionSaveFailed => 'Failed to save session';
  @override
  String get goalCompleted => 'Goal Completed!';
  @override
  String get goalCurrentProgress => 'Current Progress';
  @override
  String get goalSessionsPerWeek => 'sessions per week';
  @override
  String get goalWeekly => 'Weekly Goal';
  @override
  String get moodCalm => 'Calm';
  @override
  String get moodCheckin => 'How are you feeling?';
  @override
  String get moodEnergetic => 'Energetic';
  @override
  String get moodFocused => 'Focused';
  @override
  String get moodNeutral => 'Neutral';
  @override
  String get moodStressed => 'Stressed';
  @override
  String get moodTired => 'Tired';
  @override
  String get navAnalytics => 'Analytics';
  @override
  String get navGoals => 'Goals';
  @override
  String get navSessions => 'Sessions';
  @override
  String get navSettings => 'Settings';
  @override
  String get onboardingGetStarted => 'Get Started';
  @override
  String get onboardingNext => 'Next';
  @override
  String get onboardingSkip => 'Skip';
  @override
  String get onboardingStep1Desc => 'Build better focus habits with guided sessions';
  @override
  String get onboardingStep1Title => 'Welcome to Focus Training';
  @override
  String get onboardingStep2Desc => 'See how your focus improves over time';
  @override
  String get onboardingStep2Title => 'Track Your Progress';
  @override
  String get onboardingStep3Desc => 'Set weekly targets and build consistency';
  @override
  String get onboardingStep3Title => 'Achieve Your Goals';
  @override
  String get proFeatureDataExport => 'Export Your Data';
  @override
  String get proFeatureKeywordExtraction => 'Session Keyword Analysis';
  @override
  String get proFeatureMoodInsights => 'Mood-Focus Correlations';
  @override
  String get proFeatureTagAnalytics => 'Advanced Tag Analytics';
  @override
  String get proFeatureUnlimitedHistory => 'Complete Session History';
  @override
  String get proFreeTrial => 'Start Free Trial';
  @override
  String get proLocked => 'Pro Feature';
  @override
  String get proMonthly => 'Monthly';
  @override
  String get proSavePercent => 'Save 20%';
  @override
  String get proSubtitle => 'Unlock Advanced Analytics';
  @override
  String get proTitle => 'MindTrainer Pro';
  @override
  String get proUnlockHint => 'Tap to unlock with Pro';
  @override
  String get proUpgrade => 'Upgrade to Pro';
  @override
  String get proYearly => 'Yearly';
  @override
  String get purchaseCheckStatus => 'Check status';
  @override
  String get purchasePending => 'Purchase pending confirmation';
  @override
  String get purchaseTimeoutMessage => 'Still waiting on Google Play... You can close this message.';
  @override
  String get purchaseWaiting => 'Waiting for Google Play...';
  @override
  String get qualityExcellent => 'Excellent';
  @override
  String get qualityFair => 'Fair';
  @override
  String get qualityGood => 'Good';
  @override
  String get qualityPoor => 'Poor';
  @override
  String get qualityVeryGood => 'Very Good';
  @override
  String get restoreTimeout => 'Restore timed out. Try again.';
  @override
  String get sessionDiscard => 'Discard';
  @override
  String get sessionDuration => 'Duration';
  @override
  String get sessionNotesPlaceholder => 'Session notes (optional)';
  @override
  String get sessionQualityRating => 'How was your focus?';
  @override
  String get sessionSave => 'Save Session';
  @override
  String get sessionTagsPlaceholder => 'Add tags...';
  @override
  String get sessionTitle => 'Focus Session';
  @override
  String get settingsAbout => 'About';
  @override
  String get settingsDataExport => 'Export Data';
  @override
  String get settingsEnglish => 'English';
  @override
  String get settingsHighContrast => 'High Contrast';
  @override
  String get settingsLanguage => 'Language';
  @override
  String get settingsNotifications => 'Notifications';
  @override
  String get settingsPrivacy => 'Privacy';
  @override
  String get settingsReminderTime => 'Reminder Time';
  @override
  String get settingsSpanish => 'Spanish';
  @override
  String get settingsSupport => 'Support';
  @override
  String get settingsSystemLanguage => 'System Language';
  @override
  String get settingsTitle => 'Settings';
  @override
  String get settingsVersion => 'Version';
  @override
  String get splashInitializing => 'Initializing MindTrainer';
  @override
  String get splashLoading => 'Loading...';
  @override
  String get startBeginJourney => 'Begin Your Focus Journey';
  @override
  String get startContinueTraining => 'Continue Training';
  @override
  String get startFirstSession => 'Start Your First Session';
  @override
  String get startWelcome => 'Welcome to MindTrainer';
  @override
  String get streakDaily => 'Daily Streak';
  @override
  String get streakDays => 'days';
  @override
  String get streakWeekly => 'Weekly Streak';
  @override
  String get streakWeeks => 'weeks';
  @override
  String get supportBundleCreated => 'Support bundle created';
  @override
  String get supportContact => 'Contact Support';
  @override
  String get supportCreateBundle => 'Create Support Bundle';
  @override
  String get supportExportLogs => 'Export Logs';
  @override
  String get supportLogs => 'Logs';
  @override
  String get supportTitle => 'Support & Diagnostics';
  @override
  String get timeHoursShort => 'hr';
  @override
  String get timeLastWeek => 'Last Week';
  @override
  String get timeMinutesShort => 'min';
  @override
  String get timeSecondsShort => 'sec';
  @override
  String get timeThisWeek => 'This Week';
  @override
  String get timeToday => 'Today';
  @override
  String get timeYesterday => 'Yesterday';
  @override
  String get toastGoalUpdated => 'Goal updated';
  @override
  String get toastProUnlocked => 'Pro features unlocked!';
  @override
  String get toastPurchaseRestored => 'Purchase restored';
  @override
  String get toastSessionSaved => 'Session saved successfully';
  @override
  String get toastSettingsSaved => 'Settings saved';
}

/// Strings for es locale
class AppStringsES extends AppStrings {
  @override
  String get a11yBackButton => 'Botón de retroceso';
  @override
  String get a11yCloseButton => 'Botón de cerrar';
  @override
  String get a11yMenuButton => 'Botón de menú';
  @override
  String get a11yProLockedFeature => 'Característica Pro bloqueada';
  @override
  String get a11yQualitySlider => 'Control deslizante de calificación de calidad';
  @override
  String get a11ySaveButton => 'Botón de guardar';
  @override
  String get a11ySessionTimer => 'Temporizador de sesión';
  @override
  String get actionClose => 'Cerrar';
  @override
  String get actionCopy => 'Copiar';
  @override
  String get actionDelete => 'Eliminar';
  @override
  String get actionDone => 'Hecho';
  @override
  String get actionEdit => 'Editar';
  @override
  String get actionPause => 'Pausar';
  @override
  String get actionRefresh => 'Actualizar';
  @override
  String get actionResume => 'Reanudar';
  @override
  String get actionShare => 'Compartir';
  @override
  String get actionStart => 'Iniciar';
  @override
  String get actionStop => 'Parar';
  @override
  String get analyticsAverageQuality => 'Calidad Promedio';
  @override
  String get analyticsBestStreak => 'Mejor Racha';
  @override
  String get analyticsKeywordAnalysis => 'Análisis de Palabras Clave';
  @override
  String get analyticsMoodCorrelation => 'Correlación del Estado de Ánimo';
  @override
  String get analyticsTagPerformance => 'Rendimiento de Etiquetas';
  @override
  String get analyticsTitle => 'Análisis';
  @override
  String get analyticsTotalSessions => 'Sesiones Totales';
  @override
  String get analyticsTotalTime => 'Tiempo Total';
  @override
  String get analyticsUnlimitedHistory => 'Historial Ilimitado';
  @override
  String get appName => 'MindTrainer';
  @override
  String get appSubtitle => 'Entrenamiento de Concentración para Claridad Mental';
  @override
  String get billingCancelAnytime => 'Cancelar en cualquier momento';
  @override
  String get billingCancelled => 'Compra cancelada';
  @override
  String get billingError => 'Compra fallida';
  @override
  String get billingManage => 'Gestionar Suscripción';
  @override
  String get billingProcessing => 'Procesando compra...';
  @override
  String get billingRestore => 'Restaurar Compras';
  @override
  String get billingSuccess => '¡Compra exitosa!';
  @override
  String get coachFirstTip => 'Comienza con sesiones cortas de 10 minutos';
  @override
  String get coachGoalReminder => 'No olvides tu meta semanal';
  @override
  String get coachImprovementTip => 'Intenta concentrarte en tu respiración';
  @override
  String get coachStreakMotivation => '¡Gran racha! Sigue así';
  @override
  String get coachWelcome => '¡Hola! Soy tu entrenador de concentración';
  @override
  String get diagnosticsDisabled => 'Diagnósticos deshabilitados';
  @override
  String get diagnosticsEnabled => 'Diagnósticos habilitados';
  @override
  String get diagnosticsPanel => 'Panel de Diagnósticos';
  @override
  String get dialogCancel => 'Cancelar';
  @override
  String get dialogConfirm => 'Confirmar';
  @override
  String get dialogDelete => 'Eliminar';
  @override
  String get dialogDeleteSession => '¿Eliminar esta sesión?';
  @override
  String get dialogDiscardChanges => '¿Descartar cambios?';
  @override
  String get dialogExportDataMessage => '¿Exportar tus datos de sesión como CSV?';
  @override
  String get dialogExportDataTitle => 'Exportar Datos';
  @override
  String get dialogResetData => '¿Restablecer todos los datos?';
  @override
  String get dialogSave => 'Guardar';
  @override
  String get errorBillingUnavailable => 'Servicio de facturación no disponible';
  @override
  String get errorDataExportFailed => 'Error al exportar datos';
  @override
  String get errorGeneral => 'Algo salió mal';
  @override
  String get errorInvalidInput => 'Entrada inválida';
  @override
  String get errorNetwork => 'Se requiere conexión de red';
  @override
  String get errorSessionSaveFailed => 'Error al guardar sesión';
  @override
  String get goalCompleted => '¡Meta Completada!';
  @override
  String get goalCurrentProgress => 'Progreso Actual';
  @override
  String get goalSessionsPerWeek => 'sesiones por semana';
  @override
  String get goalWeekly => 'Meta Semanal';
  @override
  String get moodCalm => 'Calmado';
  @override
  String get moodCheckin => '¿Cómo te sientes?';
  @override
  String get moodEnergetic => 'Enérgico';
  @override
  String get moodFocused => 'Concentrado';
  @override
  String get moodNeutral => 'Neutral';
  @override
  String get moodStressed => 'Estresado';
  @override
  String get moodTired => 'Cansado';
  @override
  String get navAnalytics => 'Análisis';
  @override
  String get navGoals => 'Metas';
  @override
  String get navSessions => 'Sesiones';
  @override
  String get navSettings => 'Configuración';
  @override
  String get onboardingGetStarted => 'Comenzar';
  @override
  String get onboardingNext => 'Siguiente';
  @override
  String get onboardingSkip => 'Omitir';
  @override
  String get onboardingStep1Desc => 'Construye mejores hábitos de concentración con sesiones guiadas';
  @override
  String get onboardingStep1Title => 'Bienvenido al Entrenamiento de Concentración';
  @override
  String get onboardingStep2Desc => 'Ve cómo mejora tu concentración con el tiempo';
  @override
  String get onboardingStep2Title => 'Sigue Tu Progreso';
  @override
  String get onboardingStep3Desc => 'Establece objetivos semanales y construye consistencia';
  @override
  String get onboardingStep3Title => 'Alcanza Tus Metas';
  @override
  String get proFeatureDataExport => 'Exportar Tus Datos';
  @override
  String get proFeatureKeywordExtraction => 'Análisis de Palabras Clave de Sesión';
  @override
  String get proFeatureMoodInsights => 'Correlaciones Estado de Ánimo-Concentración';
  @override
  String get proFeatureTagAnalytics => 'Análisis Avanzado de Etiquetas';
  @override
  String get proFeatureUnlimitedHistory => 'Historial Completo de Sesiones';
  @override
  String get proFreeTrial => 'Iniciar Prueba Gratuita';
  @override
  String get proLocked => 'Característica Pro';
  @override
  String get proMonthly => 'Mensual';
  @override
  String get proSavePercent => 'Ahorra 20%';
  @override
  String get proSubtitle => 'Desbloquea Análisis Avanzados';
  @override
  String get proTitle => 'MindTrainer Pro';
  @override
  String get proUnlockHint => 'Toca para desbloquear con Pro';
  @override
  String get proUpgrade => 'Actualizar a Pro';
  @override
  String get proYearly => 'Anual';
  @override
  String get purchaseCheckStatus => 'Verificar estado';
  @override
  String get purchasePending => 'Compra pendiente de confirmación';
  @override
  String get purchaseTimeoutMessage => 'Aún esperando Google Play... Puedes cerrar este mensaje.';
  @override
  String get purchaseWaiting => 'Esperando Google Play...';
  @override
  String get qualityExcellent => 'Excelente';
  @override
  String get qualityFair => 'Regular';
  @override
  String get qualityGood => 'Bueno';
  @override
  String get qualityPoor => 'Pobre';
  @override
  String get qualityVeryGood => 'Muy Bueno';
  @override
  String get restoreTimeout => 'Restauración agotó tiempo. Inténtalo de nuevo.';
  @override
  String get sessionDiscard => 'Descartar';
  @override
  String get sessionDuration => 'Duración';
  @override
  String get sessionNotesPlaceholder => 'Notas de sesión (opcional)';
  @override
  String get sessionQualityRating => '¿Cómo estuvo tu concentración?';
  @override
  String get sessionSave => 'Guardar Sesión';
  @override
  String get sessionTagsPlaceholder => 'Agregar etiquetas...';
  @override
  String get sessionTitle => 'Sesión de Concentración';
  @override
  String get settingsAbout => 'Acerca de';
  @override
  String get settingsDataExport => 'Exportar Datos';
  @override
  String get settingsEnglish => 'Inglés';
  @override
  String get settingsHighContrast => 'Alto Contraste';
  @override
  String get settingsLanguage => 'Idioma';
  @override
  String get settingsNotifications => 'Notificaciones';
  @override
  String get settingsPrivacy => 'Privacidad';
  @override
  String get settingsReminderTime => 'Hora de Recordatorio';
  @override
  String get settingsSpanish => 'Español';
  @override
  String get settingsSupport => 'Soporte';
  @override
  String get settingsSystemLanguage => 'Idioma del Sistema';
  @override
  String get settingsTitle => 'Configuración';
  @override
  String get settingsVersion => 'Versión';
  @override
  String get splashInitializing => 'Inicializando MindTrainer';
  @override
  String get splashLoading => 'Cargando...';
  @override
  String get startBeginJourney => 'Comienza Tu Viaje de Concentración';
  @override
  String get startContinueTraining => 'Continuar Entrenamiento';
  @override
  String get startFirstSession => 'Comienza Tu Primera Sesión';
  @override
  String get startWelcome => 'Bienvenido a MindTrainer';
  @override
  String get streakDaily => 'Racha Diaria';
  @override
  String get streakDays => 'días';
  @override
  String get streakWeekly => 'Racha Semanal';
  @override
  String get streakWeeks => 'semanas';
  @override
  String get supportBundleCreated => 'Paquete de soporte creado';
  @override
  String get supportContact => 'Contactar Soporte';
  @override
  String get supportCreateBundle => 'Crear Paquete de Soporte';
  @override
  String get supportExportLogs => 'Exportar Registros';
  @override
  String get supportLogs => 'Registros';
  @override
  String get supportTitle => 'Soporte y Diagnósticos';
  @override
  String get timeHoursShort => 'h';
  @override
  String get timeLastWeek => 'Semana Pasada';
  @override
  String get timeMinutesShort => 'min';
  @override
  String get timeSecondsShort => 'seg';
  @override
  String get timeThisWeek => 'Esta Semana';
  @override
  String get timeToday => 'Hoy';
  @override
  String get timeYesterday => 'Ayer';
  @override
  String get toastGoalUpdated => 'Meta actualizada';
  @override
  String get toastProUnlocked => '¡Características Pro desbloqueadas!';
  @override
  String get toastPurchaseRestored => 'Compra restaurada';
  @override
  String get toastSessionSaved => 'Sesión guardada exitosamente';
  @override
  String get toastSettingsSaved => 'Configuración guardada';
}

/// Get strings for a specific locale
AppStrings getStrings(String localeCode) {
  switch (localeCode) {
    case 'en':
      return AppStringsEN();
    case 'es':
      return AppStringsES();
    default:
      return AppStringsEN(); // Default to first locale
  }
}

/// Extension to get strings from BuildContext
extension StringsExtension on BuildContext {
  AppStrings get strings {
    final locale = Localizations.localeOf(this);
    final localeCode = locale.languageCode;
    return getStrings(localeCode);
  }
}
