name: android-release

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags: ['v*.*.*']  # Version tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Decode Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/mindtrainer-upload.jks
          
      - name: Create key.properties
        run: |
          cat > android/key.properties << EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=../app/mindtrainer-upload.jks
          EOF
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
        
      - name: Build AAB
        run: |
          flutter build appbundle \
            --release \
            --flavor prod \
            --build-number=${{ github.run_number }} \
            --split-debug-info=build/symbols \
            --obfuscate
        env:
          JAVA_TOOL_OPTIONS: -Xmx4g
          
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          
      - name: Upload mapping file
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: build/app/outputs/mapping/prodRelease/mapping.txt
          
      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: symbols
          path: build/symbols/
          
      - name: Upload to Play Store
        if: startsWith(github.ref, 'refs/tags/')
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON_KEY }}
          packageName: com.mindtrainer.mindtrainer
          releaseFiles: build/app/outputs/bundle/prodRelease/app-prod-release.aab
          track: internal
          mappingFile: build/app/outputs/mapping/prodRelease/mapping.txt